- name: install make
  sudo: true
  apt: name=make state=present

- name: install build-essential
  sudo: true
  apt: name=build-essential state=present

- name: install libssl-dev
  sudo: true
  apt: name=libssl-dev state=present

- name: install zlib1g-dev
  sudo: true
  apt: name=zlib1g-dev state=present

- name: install libbz2-dev
  sudo: true
  apt: name=libbz2-dev state=present

- name: install libreadline-dev
  sudo: true
  apt: name=libreadline-dev state=present

- name: install libsqlite3-dev
  sudo: true
  apt: name=libsqlite3-dev state=present

- name: install wget
  sudo: true
  apt: name=wget state=present

- name: install curl
  sudo: true
  apt: name=curl state=present

- name: install llvm
  sudo: true
  apt: name=llvm state=present

- name: clone pyenv
  git: repo=https://github.com/yyuu/pyenv.git dest=~/.pyenv version=HEAD

- name: clone pyenv-virtualenv
  git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=~/.pyenv/plugins/pyenv-virtualenv version=HEAD

- name: install pyenvrc
  copy: src=pyenvrc dest=~/.pyenvrc

- name: source pyenvrc
  lineinfile: dest=~/.bash_aliases line="source .pyenvrc" create=yes

- name: check for python
  stat: path=~/.pyenv/versions/2.7.8
  register: python
  changed_when: False

- name: install python
  shell: . ~/.pyenvrc && pyenv install 2.7.8
  when: python.stat.exists == false

- name: check for virtualenv
  stat: path=~/.pyenv/versions/default
  register: virtualenv
  changed_when: false

- name: create virtualenv
  shell: . ~/.pyenvrc && pyenv virtualenv 2.7.8 default
  when: virtualenv.stat.exists == false

- name: check for global virtualenv
  stat: path=~/.pyenv/version
  register: pyenv_version

- name: set default virtualenv
  shell: . ~/.pyenvrc && pyenv global default
  when: pyenv_version.stat.exists == false
