---
- name: Install unzip
  apt: name=unzip state=present

- name: Install supervisor
  apt: name=supervisor

- name: Download serf
  get_url:
    url=https://dl.bintray.com/mitchellh/serf/{{version}}_linux_amd64.zip
    dest=/tmp

- name: Check for serf
  stat: path=/usr/local/bin/serf
  register: serf
  changed_when: false

- name: Unzip serf
  command: unzip /tmp/{{version}}_linux_amd64.zip -d /usr/local/bin/
  when: serf.stat.exists == false

- name: Copy supervisord-serf.conf
  copy: src=supervisord-serf.conf dest=/etc/supervisor/conf.d/supervisord-serf.conf mode=0755

- name: Retart supervisor
  service: name=supervisor state=restarted
