---
- name: Install unzip
  apt: name=unzip state=present

- name: Install supervisor
  apt: name=supervisor

- name: Download serf
  get_url:
    url=https://dl.bintray.com/mitchellh/serf/{{version}}_linux_amd64.zip
    dest=/tmp

- name: Check for serf
  stat: path=/usr/local/bin/serf
  register: serf
  changed_when: false

- name: Unzip serf
  unarchive: src=/tmp/{{version}}_linux_amd64.zip  dest=/usr/local/bin copy=false
  when: serf.stat.exists == false

- name: Copy supervisord-serf.conf
  template: src=supervisord-serf.conf.j2 dest=/etc/supervisor/conf.d/supervisord-serf.conf mode=0755

- name: Copy openvswitch-handler.sh
  copy: src=openvswitch-handler.sh dest=/openvswitch-handler.sh mode=0755

- name: Reload supervisor config
  command: supervisorctl update
  register: update_result
  changed_when: update_result == ''
