---
- hosts: all
  tasks:
    - name: install make
      apt: name=make state=present
    - name: install build-essential
      apt: name=build-essential state=present
    - name: install libssl-dev
      apt: name=libssl-dev state=present
    - name: install zlib1g-dev
      apt: name=zlib1g-dev state=present
    - name: install libbz2-dev
      apt: name=libbz2-dev state=present
    - name: install libreadline-dev
      apt: name=libreadline-dev state=present
    - name: install libsqlite3-dev
      apt: name=libsqlite3-dev state=present
    - name: install wget
      apt: name=wget state=present
    - name: install curl
      apt: name=curl state=present
    - name: install llvm
      apt: name=llvm state=present
    - name: clone pyenv
      git: repo=https://github.com/yyuu/pyenv.git dest=~/.pyenv version=HEAD
    - name: clone pyenv-virtualenv
      git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=~/.pyenv/plugins/pyenv-virtualenv version=HEAD
    - name: install pyenvrc
      copy: src=pyenvrc dest=~/.pyenvrc
    - name: source pyenvrc
      lineinfile: dest=~/.bash_aliases line="source .pyenvrc" create=yes
    - name: install python
      shell: . ~/.pyenvrc && pyenv install 2.7.8 -s
    - name: create virtualenv
      shell: . ~/.pyenvrc && echo -n n | pyenv virtualenv 2.7.8 default || true
    - name: set default virtualenv
      shell: . ~/.pyenvrc && pyenv global default
