---
- hosts: all
  vars:
    version: 0.6.3
  tasks:
    - get_url:
        url="https://dl.bintray.com/mitchellh/serf/{{version}}_linux_amd64.zip"
        dest="/tmp"
      register: get_serf
    - name: Install unzip
      apt: name=unzip state=installed update_cache=true
    - name: Unzip serf
      command: unzip /tmp/{{version}}_linux_amd64.zip
    - name: Move serf executable to path
      copy: src=/tmp/serf dest=/usr/local/bin/serf owner=vagrant mode=0711

    - debug:
        msg="serf was downloaded"
      when: get_serf|changed
